# libs =
# import libs += libbrot%lib{brot}

include ../../libbrot/libbrot/

# exe{brot}: {hxx ixx txx cxx}{**} $libs testscript
exe{brot}: {hxx ixx txx cxx}{**} ../../libbrot/libbrot/lib{brot} testscript

cxx.poptions =+ "-I$out_root" "-I$src_root" "-g3"
